alter table dbesusgestor.tb_resultado add column co_seq_categoria_analise_item integer;
alter table dbesusgestor.tb_resultado add constraint fk_tb_resultado_co_seq_categoria_analise_item FOREIGN KEY (co_seq_indicador) REFERENCES dbesusgestor.tb_categoria_analise_item(co_seq_categoria_analise_item);
