# swagger configuration file

# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

# any other values in this file are just loaded into the config for application access...
config:
  host: localhost:8000
  secret: bZJc2sWbQLKos6GkHn/VB9oXwQt8S0R0kRvJ5/xJ89A=
  # -------------------------------------------
  # | Banco de dados do MGI                   |
  # -------------------------------------------
  database: dbspo
  user: postgres
  password: pass
  hostdb: localhost
  ##hostdb: banco
  # -------------------------------------------
  # | Tabela interna de resultados            |
  # -------------------------------------------
  tabela_indicadores: tb_resultado
  schema_esusgestor: dbesusgestor
  # -------------------------------------------
  # | SCPA                                    |
  # -------------------------------------------
  schema_login: scpa
  wsdl: http://aplicacao-homologacao.saude.gov.br/datasus-scpa-ws/ScpaServiceImpl?wsdl
  system: SAGE
  # -------------------------------------------
  # | LDAP                                    |
  # -------------------------------------------
  #schema_login: ldap
  #url: 'ldap://localhost'
  #bindDn: 'cn=admin, dc=synapsys, dc=com, dc=br'
  #bindCredentials: 'gFGcZxyrnc8pT8se'
  #searchBase: 'DC=synapsys, DC=com, DC=br'
  #searchFilter: '(uid={{username}})'
  # -------------------------------------------
  # | Documentacao                            |
  # -------------------------------------------
  title: eSUSGestor - API de comunicação
  description: |
    A estratégia e-Saúde, sob a óptica de TI, é uma plataforma concebida como um conjunto de soluções que trabalham de maneira independente e descentralizada, porém articulada, coordenada e integrada – como o próprio SUS.
    # Introdução
    O projeto visa a criação de um barramento para intermediar o acesso a informações visando uma estratégia de negócio coerente e padronizada.  Esse barramento vai incorporar características de segurança como login no SCPA (ou outro sistema de segurança).  As funcionalidades previstas serão plugáveis e terá como início o módulo de gestão de indicadores MGI  e será extendido para as funcionalidades necessárias as consultas demandadas pelo eSUS Gestor.  O desenvolvimento segue os padrões requeridos pelo DATASUS em seu documento de definição [Diretriz arquitetural de software](https://integrams.saude.gov.br/uploadfile/getFile?coUploadFile=24907)
    # Objetivo
    *  Capacidade de identificar o usuário intermediando a autenticação e provendo a autorização necessária segundo integração com o SCPA ou qualquer outro sistema de autenticação.
    *  Utilização de metadados para criação de consultas dinâmicas as bases
    *  Implementação de protocolo textuais abertos para comunicação (REST/JSON).

    # Especificação API eSUSGestor
    Esta API está documentada no formato **OpenAPI** e é disponibilizada no endereço [API eSUSGestor](http://rest.demas.saude.gov).

    Interface para acesso e lista de [endpoints](http://rest.demas.saude.gov).
