apps:
  - script   : ./app.js
    name: barramento-api
    instances: 1
    exec_mode: cluster
    watch  : true
    env    :
      NODE_ENV: dev
      COMPANY: MS
      HOSTDB: 192.168.0.25
      PGPORT: 5432
      DATABASE: dbdigisus
      USER_DB: luiscrneves
      PASSWORD_DB: 130670
      SCHEMA: dbesusgestor
      HOST: localhost:8001
      SCHEMA_LOGIN: scpa
      WSDL: http://aplicacao.saude.gov.br/datasus-scpa-ws/ScpaServiceImpl?wsdl
      SISTEMA: SAGE
      LOGGING_SQ: false
